name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          # - x86_64-pc-windows-gnu]
    steps:
    - uses: actions/checkout@v2
    - name: Rust Version
      run: |
        rustc -Vv
        cargo -V
      shell: bash
    - name: Install target
      run: rustup target add ${{ matrix.target }}
    - name: Bench
      run: cargo bench --target ${{ matrix.target }}
      shell: bash
